spring:
  data:
    mongodb:
      uri: mongodb+srv://omar:FcybyLAxvwU6nsxT@cluster0.kp2s5.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
#      uri: mongodb://localhost:27017
      database: users
server:
  port: 9001